src/Models/EncryptionSubject.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Encryptor.Models
{
    public class EncryptionSubject
    {
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "requiredText")]
        public string PlainText { get; set; }
        
        [DataType(DataType.Text)]
        public string EncryptedText { get; set; }
    }
}

src/Models/ErrorViewModel.cs
using System;

namespace Encryptor.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Controllers/CultureController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Http;

namespace Encryptor.Controllers
{
    public class CultureController : Controller
    {
        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

src/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Encryptor.Models;
using Encryptor.Services;
using Encryptor.Services.Exceptions;

namespace Encryptor.Controllers
{
    public class HomeController : Controller
    {
        private readonly IEncryptionService _encryptionService; 
        private readonly IResultFormatter _tagFormatterService; 

        public HomeController(IEncryptionService encryptionService, IResultFormatter tagFormatterService) 
        { 
            _encryptionService = encryptionService; 
            _tagFormatterService = tagFormatterService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new EncryptionSubject());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index([Bind("PlainText")] EncryptionSubject subject)
        {
            if (ModelState.IsValid) {
                try 
                {
                    this._encryptionService.encrypt(subject);
                    this._tagFormatterService.format(subject);
                }
                catch (MessageTooLongException) {
                    ViewData["isMessageTooLong"] = true;
                }
            }
            return View(subject);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Views/Home/Index.cshtml
@model Encryptor.Models.EncryptionSubject

@{
    ViewData["Title"] = @Localizer["IndexTitle"];
}

@section Messages {
    @if (ViewBag.isMessageTooLong != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>@Localizer["MessageTooLong"]</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}

<div class="row">
    <div class="col">
        <form asp-action="Index">
            <div class="form-group px-3">
                <label class="form-label" for="TextToEncrypt">@Localizer["TextAreaLabel"]</label>
                <textarea 
                    name="PlainText"
                    class="form-control" 
                    rows="10" 
                    id="TextToEncrypt" 
                    value="" 
                    placeholder="@Localizer["TextAreaPlaceHolder"]">@Model.PlainText</textarea>
                    <div style="min-height: 25px;">
                       <span asp-validation-for="PlainText" class="text-danger"></span>
                    </div>
            </div>

            <div class="px-3 text-center">
                <button class="btn btn-success btn-sm" type="submit"><i class="fa fa-check"></i> @Localizer["SubmitButton"]</button>
                <button type="button" onclick="location.href='@Url.Action("Index", "Home")'" class="btn btn-danger btn-sm"><i class="fa fa-times"></i> @Localizer["Reset"]</button>
            </div>

            <div class="form-group px-3 pt-5 pb-3">
                <label class="form-label" for="EncryptedText">@Localizer["TextAreaEncryptedLabel"]</label>
                <div class="card">
                    <div id="encryptedSecret" class="card-body resultPanel" data-placeholder="@Localizer["TextAreaEncryptedPlaceHolder"]">@Model.EncryptedText</div>
                </div>
            </div>

            <div class="px-3 text-center">
                <button 
                    id="copyButton"
                    class="btn btn-success btn-sm"
                    type="button"
                    onclick="copyToClipboard('@Model.EncryptedText');" 
                    @if(@Model.EncryptedText == null) { 
                        @: disabled
                    }>
                    <i class="fa fa-files-o"></i> @Localizer["Copy"]
                </button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    
    <script type="text/javascript">
        $( document ).ready(function() {
            $("#copyButton").trigger("click");
        });
    </script>
}

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Localizer["AppName"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="mx-5 my-2 pr-2 w-100">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/logo.png" class="img-responsive" style="margin-top: -8px; height: 33px; margin-right: 5px;" asp-append-version="true">
                        @Localizer["AppName"]
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    @await Html.PartialAsync("_SelectLanguagePartial")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="px-5 py-3 m-5 main-box">
                <div class="row align-items-center" style="min-height: 80px">
                    <div class="col">
                        @RenderSection("Messages", required: false)
                    </div>
                </div>
                @RenderBody()
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="footer-div">
                <a href="http://www.beubi.com/">
                    <img style="height: 25px;" id="beubilogo" src="~/images/beubi_logo.png" alt="be.ubi" title="be.ubi">
                </a>
                 <br />
                <span>@Localizer["PoweredBy"] </span>
                <script> document.write(new Date().getFullYear()); </script>
            </div>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true" defer></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/Views/Shared/_SelectLanguagePartial.cshtml
@using System.Threading.Tasks
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div title="@Localizer["language"]" class="float-right mt-2">
    <form id="selectLanguage" 
          asp-controller="Culture" 
          asp-action="SetLanguage"
          asp-action="SetLanguage" 
          asp-route-returnUrl="@(Context.Request.PathBase.HasValue ? Context.Request.PathBase : Context.Request.Path)"
          method="post" 
          class="form-horizontal" 
          role="form">

           <div class="form-row align-items-center">

    <div class="col-auto">
      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text" style="height: 30px;"><i class="fa fa-language" aria-hidden="true"></i></div>
        </div>
         <select class="form-control" name="culture" style="height: 30px; font-size: 12px;"
                                        asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
    
      </div>
    </div>

        
    
    </form>
</div>